name: Build and Deploy

on:
  push:
    branches:
      - main  # Adjust if you are using a different branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # Specify the PHP version you are using

    - name: Install Composer dependencies
      run: composer install

    - name: Generate dbconfig.php
      run: |
        echo "<?php" > dbconfig.php
        echo "\$host = '${{ vars.CG_DATABASE_HOST }}';" >> dbconfig.php
        echo "\$database = '${{ vars.CG_DATABASE }}';" >> dbconfig.php
        echo "\$user = '${{ vars.CG_DATABASE_USER }}';" >> dbconfig.php
        echo "\$password = '${{ secrets.CG_DATABASE_PASSWORD }}';" >> dbconfig.php
        echo "\$returnUrl = '${{ vars.PAYPAL_RETURN_URL }}';" >> dbconfig.php;
        echo "\$cancelUrl = '${{ vars.PAYPAL_CANCEL_URL }}';" >> dbconfig.php;

        echo "?>" >> dbconfig.php

    - name: Build project
      run: |
        # Add any build steps if required
        echo "Build step (if any) goes here."

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4
      with:
        server: ${{ vars.CG_SERVER }}
        username: ${{ vars.CG_FTP_USERNAME }}
        password: ${{ secrets.CG_FTP_PASSWORD }}
        local-dir: ./
        server-dir: ${{ vars.SERVER_DIR }}
        git-ftp-args: --insecure

    - name: Clean up
      run: rm dbconfig.php
